spring:
  application:
    name: ms-spring-secure-gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: 'http://localhost:8001'
          predicates:
            - Path=/api/v1/service1/**
          filters:
            - AddRequestHeader=X-Request-Id, 1234
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET, POST
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
                  requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

        - id: service2
          uri: 'http://localhost:8002'
          predicates:
            - Path=/api/v1/service2/**
          filters:
            - AddRequestHeader=X-Request-Id, 1234
    config:
      enabled: false
  config:
    import: optional:configserver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

  main:
    web-application-type: reactive


management:
  endpoints:
    web:
      exposure:
        include: gateway

  tracing:
    sampling:
      probability: 0.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans


server:
  port: 8081
